### ISSUE TITLE
Validator should not end validation on "invalid content type"

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/lkod-validator#1]
This [test catalog](https://raw.githubusercontent.com/linkedpipes/lkod-tests/main/dcat-ap-dokumenty/nevalidní/n01.jsonld) has invalid JSON syntax. Yet the validator ends with "Invalid content type 'text/plain'." Since it does the same also for syntactically [correct JSON catalog](https://raw.githubusercontent.com/linkedpipes/lkod-tests/main/dcat-ap-dokumenty/nevalidní/n02.jsonld) I think this is not a good behavior. It should issue a warning and try to guess the data format anyway, e.g. based on the extension, trying to query it using SPARQL, loading it as JSON, JSON-LD and Turtle, etc.

**Comment by skodapetr** [comment]
Using SPARQL ASK is the first option even before downloading the resource as agreed upon. I'm not sure about just loading the data at random where no type indication (type header, or extension) is provided. Is this really desired feature?

**Comment by jakubklimek** [comment]
I think header and extension support should be enough.
